const fileConstants = {
  FILES_REQUEST: 'FILES_REQUEST',
  FILES_SUCCESS: 'FILES_SUCCESS',
  FILES_FAILURE: 'FILES_FAILURE',

  ADD_TO_FAV_REQUEST: 'ADD_TO_FAV_REQUEST',
  ADD_TO_FAV_SUCCESS: 'ADD_TO_FAV_SUCCESS',
  ADD_TO_FAV_FAILURE: 'ADD_TO_FAV_FAILURE',

  REMOVE_FROM_FAV_REQUEST: 'REMOVE_FROM_FAV_REQUEST',
  REMOVE_FROM_FAV_SUCCESS: 'REMOVE_FROM_FAV_SUCCESS',
  REMOVE_FROM_FAV_FAILURE: 'REMOVE_FROM_FAV_FAILURE',

  DELETE_REQUEST: 'DELETE_REQUEST',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAILURE: 'DELETE_FAILURE',

  PUBLIC_SHAREABLE_LINK_REQUEST: 'PUBLIC_SHAREABLE_LINK_REQUEST',
  PUBLIC_SHAREABLE_LINK_SUCCESS: 'PUBLIC_SHAREABLE_LINK_SUCCESS',
  PUBLIC_SHAREABLE_LINK_FAILURE: 'PUBLIC_SHAREABLE_LINK_FAILURE',
};

export default fileConstants;
