name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/storage-drive-backend.git
      - name: Deploy backend to Heroku
        run: git push heroku-server `git subtree split --prefix server master`:master --force
