name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add heroku-client https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/storage-drive-frontend.git
      - name: Deploy frontend to Heroku
        run: git push heroku-client `git subtree split --prefix client master`:master --force
